import { forceUpdate } from "@stencil/core";
import { GanttPlannerDetailsProps, GanttPlannerProps, KupPlannerGanttRow, KupPlannerGanttTaskN, KupPlannerItemDetail, KupPlannerTaskType, PlannerProps } from "../kup-planner-declarations";

function dummyFilter() {
    const filter = document.createElement("div");
    filter.innerText = "Filter placeholder";
    return filter;
}

const onScrollX = (x: number) => {
    console.log("Planner scrollX event", x);
};

const onScrollY = (value: number) => {
    console.log("SCROLL Y", value);
}

const mainGanttDoubleViewHandler = (checked: boolean) => {
    console.log("Main Gantt double view slider event", checked);
};

let isClicked = false;
const mainGanttClickHandler = (row: KupPlannerGanttRow) => {
    console.log("Main Gantt click event", row);
    // if (row.type === "project") {
    //     if (isClicked) {
    //         mainGanttPlanner1PropsMock.items = mainGanttPlaner1ItemsAfterClick;
    //     } else {
    //         mainGanttPlanner1PropsMock.items = mainGanttPlaner1Items;
    //     }
    //     isClicked = !isClicked;
    // }
};
// // planner 1

const mainGanttPlaner1Items: any = [
    {
        id: "1",
        name: "G456",
        startDate: "2021-10-25",
        endDate: "2023-11-20",
        secondaryStartDate: "2021-10-25",
        secondaryEndDate: "2023-03-07",
        type: "project",
        phases: [],
        details: [],
        valuesToShow: ["G456", "#START#", "#END#"],
        icon: {
            color: "#FF0000",
            url: "http://localhost:3000/assets/svg/alert-circle.svg",
        },
    },
    {
        id: "2",
        name: "G460",
        startDate: "2021-10-20",
        endDate: "2023-04-07",
        secondaryStartDate: "2021-10-20",
        secondaryEndDate: "2022-12-16",
        type: "project",
        phases: [],
        details: [],
        valuesToShow: ["G460", "#START#", "#END#"],
    },
]

const mainGanttPlaner1ItemsAfterClick: any = [
    {
        id: "1",
        name: "G456",
        startDate: "2021-10-25",
        endDate: "2023-11-20",
        secondaryStartDate: "2021-10-25",
        secondaryEndDate: "2023-03-07",
        type: "project",
        valuesToShow: ["G456", "#START#", "#END#"],
        icon: {
            color: "#FF0000",
            url: "http://localhost:3000/assets/svg/alert-circle.svg",
        },
        phases: [
            {
                id: "P410           ",
                name: "P410           ",
                startDate: "2023-03-10",
                endDate: "2023-10-17",
                secondaryStartDate: "2022-11-04",
                secondaryEndDate: "2022-11-07",
                color: "#ED7D31",
                selectedColor: "#ED7D31",
                valuesToShow: ["P410", "#START#", "#END#"],
                dependencies: [],
                type: "task",
                icon: {
                    color: "#FF0000",
                    url: "http://localhost:3000/assets/svg/alert-circle.svg",
                },
            },
            {
                id: "P420           ",
                name: "P420           ",
                startDate: "2022-11-21",
                endDate: "2023-03-10",
                secondaryStartDate: "2023-01-13",
                secondaryEndDate: "2022-11-11",
                color: "#FF0000",
                selectedColor: "#FF0000",
                valuesToShow: ["P420", "#START#", "#END#"],
                dependencies: [],
                type: "task",
            },
            {
                id: "P610           ",
                name: "P610           ",
                startDate: "2023-03-27",
                endDate: "2023-04-14",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2023-01-02",
                color: "#70AD47",
                selectedColor: "#70AD47",
                valuesToShow: ["P610", "#START#", "#END#"],
                dependencies: ["P410           "],
                type: "task",
            },
            {
                id: "P620           ",
                name: "P620           ",
                startDate: "2023-03-27",
                endDate: "2023-04-14",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2022-11-30",
                color: "#C6E0B4",
                selectedColor: "#C6E0B4",
                valuesToShow: ["P620", "#START#", "#END#"],
                dependencies: ["P410           "],
                type: "task",
            },
            {
                id: "P630           ",
                name: "P630           ",
                startDate: "2023-03-20",
                endDate: "2023-04-07",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2022-12-21",
                color: "#BDD7EE",
                selectedColor: "#BDD7EE",
                valuesToShow: ["P630", "#START#", "#END#"],
                dependencies: ["P410           "],
                type: "task",
            },
            {
                id: "P710           ",
                name: "P710           ",
                startDate: "2023-04-17",
                endDate: "2023-04-28",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2023-01-10",
                color: "#FFFF00",
                selectedColor: "#FFFF00",
                valuesToShow: ["P710", "#START#", "#END#"],
                dependencies: ["P610           "],
                type: "task",
            },
            {
                id: "P720           ",
                name: "P720           ",
                startDate: "2023-05-02",
                endDate: "2023-05-10",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2023-01-17",
                color: "#BDD7EE",
                selectedColor: "#BDD7EE",
                valuesToShow: ["P720", "#START#", "#END#"],
                dependencies: ["P710           "],
                type: "task",
            },
            {
                id: "P730           ",
                name: "P730           ",
                startDate: "2023-05-17",
                endDate: "2023-05-30",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2023-01-31",
                color: "#F8CBAD",
                selectedColor: "#F8CBAD",
                valuesToShow: ["P730", "#START#", "#END#"],
                dependencies: ["P720           "],
                type: "task",
            },
            {
                id: "P750           ",
                name: "P750           ",
                startDate: "2023-05-31",
                endDate: "2023-07-04",
                secondaryStartDate: "2023-03-01",
                secondaryEndDate: "2023-03-07",
                color: "#7030A0",
                selectedColor: "#7030A0",
                valuesToShow: ["P750", "#START#", "#END#"],
                dependencies: ["P730           "],
                type: "task",
            },
        ],
    },
    {
        id: "2",
        name: "G460",
        startDate: "2021-10-20",
        endDate: "2023-04-07",
        secondaryStartDate: "2021-10-20",
        secondaryEndDate: "2022-12-16",
        type: "project",
        valuesToShow: ["G460", "#START#", "#END#"],
        phases: [
            {
                id: "G460_P410           ",
                name: "FS - MONTAGGIO MECCANICO           ",
                startDate: "2023-03-06",
                endDate: "2023-06-30",
                secondaryStartDate: "2022-06-13",
                secondaryEndDate: "2022-11-04",
                type: "task",
                color: "#ED7D31",
                selectedColor: "#ED7D31",
                valuesToShow: ["#START#", "#END#"],
            },
            {
                id: "G460_P420           ",
                name: "FS - MONTAGGIO ELETTRICO           ",
                startDate: "2022-11-21",
                endDate: "2023-02-24",
                secondaryStartDate: "2022-08-29",
                secondaryEndDate: "2022-11-11",
                type: "task",
                color: "#FF0000",
                selectedColor: "#FF0000",
                valuesToShow: ["#START#", "#END#"],
            },
            {
                id: "G460_P610           ",
                name: "FS - MESSA IN SERVIZIO MECC.       ",
                startDate: "2023-07-17",
                endDate: "2023-08-04",
                secondaryStartDate: "2022-11-21",
                secondaryEndDate: "2023-01-02",
                type: "task",
                color: "#70AD47",
                selectedColor: "#70AD47",
                valuesToShow: ["#START#", "#END#"],
            },
        ],
    },
]
const mainGanttPlanner1PropsMock: GanttPlannerProps = {
    readOnly: false,
    /*initialScrollX: 11,
    initialScrollY: 210,*/
    filter: dummyFilter(),
    items: [
        // {
        //     id: "1",
        //     name: "G456",
        //     startDate: "2021-10-25",
        //     endDate: "2023-11-20",
        //     secondaryStartDate: "2021-10-25",
        //     secondaryEndDate: "2023-03-07",
        //     type: "project",
        //     phases: [],
        //     details: [],
        //     valuesToShow: ["G456", "#START#", "#END#"],
        //     icon: {
        //         color: "#FF0000",
        //         url: "http://localhost:3000/assets/svg/alert-circle.svg",
        //     },
        // },
        // {
        //     id: "2",
        //     name: "G460",
        //     startDate: "2021-10-20",
        //     endDate: "2023-04-07",
        //     secondaryStartDate: "2021-10-20",
        //     secondaryEndDate: "2022-12-16",
        //     type: "project",
        //     phases: [],
        //     details: [],
        //     valuesToShow: ["G460", "#START#", "#END#"],
        // },
        {
            id: "1",
            name: "G456",
            startDate: "2021-10-25",
            endDate: "2023-11-20",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            valuesToShow: ["G456", "#START#", "#END#"],
            icon: {
                color: "#FF0000",
                url: "http://localhost:3000/assets/svg/alert-circle.svg",
            },
            phases: [
                {
                    id: "P410           ",
                    name: "P410           ",
                    startDate: "2023-03-10",
                    endDate: "2023-10-17",
                    secondaryStartDate: "2022-11-04",
                    secondaryEndDate: "2022-11-07",
                    color: "#ED7D31",
                    selectedColor: "#ED7D31",
                    valuesToShow: ["P410", "#START#", "#END#"],
                    dependencies: [],
                    type: "task",
                    icon: {
                        color: "#FF0000",
                        url: "http://localhost:3000/assets/svg/alert-circle.svg",
                    },
                },
                {
                    id: "P420           ",
                    name: "P420           ",
                    startDate: "2022-11-21",
                    endDate: "2023-03-10",
                    secondaryStartDate: "2023-01-13",
                    secondaryEndDate: "2022-11-11",
                    color: "#FF0000",
                    selectedColor: "#FF0000",
                    valuesToShow: ["P420", "#START#", "#END#"],
                    dependencies: [],
                    type: "task",
                },
                {
                    id: "P610           ",
                    name: "P610           ",
                    startDate: "2023-03-27",
                    endDate: "2023-04-14",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2023-01-02",
                    color: "#70AD47",
                    selectedColor: "#70AD47",
                    valuesToShow: ["P610", "#START#", "#END#"],
                    dependencies: ["P410           "],
                    type: "task",
                },
                {
                    id: "P620           ",
                    name: "P620           ",
                    startDate: "2023-03-27",
                    endDate: "2023-04-14",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2022-11-30",
                    color: "#C6E0B4",
                    selectedColor: "#C6E0B4",
                    valuesToShow: ["P620", "#START#", "#END#"],
                    dependencies: ["P410           "],
                    type: "task",
                },
                {
                    id: "P630           ",
                    name: "P630           ",
                    startDate: "2023-03-20",
                    endDate: "2023-04-07",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2022-12-21",
                    color: "#BDD7EE",
                    selectedColor: "#BDD7EE",
                    valuesToShow: ["P630", "#START#", "#END#"],
                    dependencies: ["P410           "],
                    type: "task",
                },
                {
                    id: "P710           ",
                    name: "P710           ",
                    startDate: "2023-04-17",
                    endDate: "2023-04-28",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2023-01-10",
                    color: "#FFFF00",
                    selectedColor: "#FFFF00",
                    valuesToShow: ["P710", "#START#", "#END#"],
                    dependencies: ["P610           "],
                    type: "task",
                },
                {
                    id: "P720           ",
                    name: "P720           ",
                    startDate: "2023-05-02",
                    endDate: "2023-05-10",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2023-01-17",
                    color: "#BDD7EE",
                    selectedColor: "#BDD7EE",
                    valuesToShow: ["P720", "#START#", "#END#"],
                    dependencies: ["P710           "],
                    type: "task",
                },
                {
                    id: "P730           ",
                    name: "P730           ",
                    startDate: "2023-05-17",
                    endDate: "2023-05-30",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2023-01-31",
                    color: "#F8CBAD",
                    selectedColor: "#F8CBAD",
                    valuesToShow: ["P730", "#START#", "#END#"],
                    dependencies: ["P720           "],
                    type: "task",
                },
                {
                    id: "P750           ",
                    name: "P750           ",
                    startDate: "2023-05-31",
                    endDate: "2023-07-04",
                    secondaryStartDate: "2023-03-01",
                    secondaryEndDate: "2023-03-07",
                    color: "#7030A0",
                    selectedColor: "#7030A0",
                    valuesToShow: ["P750", "#START#", "#END#"],
                    dependencies: ["P730           "],
                    type: "task",
                },
            ],
        },
        {
            id: "2",
            name: "G460",
            startDate: "2021-10-20",
            endDate: "2023-04-07",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            valuesToShow: ["G460", "#START#", "#END#"],
            phases: [
                {
                    id: "G460_P410           ",
                    name: "FS - MONTAGGIO MECCANICO           ",
                    startDate: "2023-03-06",
                    endDate: "2023-06-30",
                    secondaryStartDate: "2022-06-13",
                    secondaryEndDate: "2022-11-04",
                    type: "task",
                    color: "#ED7D31",
                    selectedColor: "#ED7D31",
                    valuesToShow: ["#START#", "#END#"],
                },
                {
                    id: "G460_P420           ",
                    name: "FS - MONTAGGIO ELETTRICO           ",
                    startDate: "2022-11-21",
                    endDate: "2023-02-24",
                    secondaryStartDate: "2022-08-29",
                    secondaryEndDate: "2022-11-11",
                    type: "task",
                    color: "#FF0000",
                    selectedColor: "#FF0000",
                    valuesToShow: ["#START#", "#END#"],
                },
                {
                    id: "G460_P610           ",
                    name: "FS - MESSA IN SERVIZIO MECC.       ",
                    startDate: "2023-07-17",
                    endDate: "2023-08-04",
                    secondaryStartDate: "2022-11-21",
                    secondaryEndDate: "2023-01-02",
                    type: "task",
                    color: "#70AD47",
                    selectedColor: "#70AD47",
                    valuesToShow: ["#START#", "#END#"],
                },
            ],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    showSecondaryDates: false,
    ganttHeight: 200,
    hideDependencies: true,
    title: "Main",
    initialScrollX: 12,
    onClick: mainGanttClickHandler,
};

const secondaryGanttPlanner1PropsMock: GanttPlannerDetailsProps = {
    readOnly: true,
    initialScrollY: 220,
    items: [
        {
            id: "RIS1",
            name: "Risorsa 1",
            schedule: [
                { startDate: "2023-01-01", endDate: "2023-02-01", color: "#ff0000" },
                {
                    startDate: "2023-03-01",
                    endDate: "2023-04-01",
                    color: "#ff0000",
                    icon: {
                        color: "#00ff00",
                        url: "http://localhost:3000/assets/svg/alert-circle.svg",
                    },
                },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 1"],
        },
        {
            id: "RIS2",
            name: "Risorsa 2",
            schedule: [
                { startDate: "2023-01-10", endDate: "2023-02-10", color: "#00ff00" },
                {
                    startDate: "2023-03-10",
                    endDate: "2023-04-10",
                    color: "#0000ff",
                    icon: {
                        color: "#00ff00",
                        url: "http://localhost:3000/assets/svg/alert-circle.svg",
                    },
                },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 2"],
        },
        {
            id: "RIS3",
            name: "Risorsa 3",
            schedule: [
                { startDate: "2023-01-15", endDate: "2023-02-15" /*color: "#ff0000"*/ },
                { startDate: "2023-03-15", endDate: "2023-04-15" /*color: "#ff0000"*/ },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 3"],
        },
        {
            id: "RIS4",
            name: "Risorsa 4",
            schedule: [
                { startDate: "2023-01-11", endDate: "2023-02-01", color: "#ff0000" },
                { startDate: "2023-03-11", endDate: "2023-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 4"],
        },
        {
            id: "RIS5",
            name: "Risorsa 5",
            schedule: [
                { startDate: "2023-01-01", endDate: "2023-02-01", color: "#ff0000" },
                { startDate: "2023-03-01", endDate: "2023-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 5"],
        },
        {
            id: "RIS6",
            name: "Risorsa 6",
            schedule: [
                { startDate: "2023-01-20", endDate: "2023-02-20", color: "#ff0000" },
                { startDate: "2023-03-20", endDate: "2023-04-20", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 6"],
        },
        {
            id: "RIS7",
            name: "Risorsa 7",
            schedule: [
                { startDate: "2023-01-01", endDate: "2023-02-01", color: "#ff0000" },
                { startDate: "2023-03-01", endDate: "2023-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 7"],
        },
        {
            id: "RIS8",
            name: "Risorsa 8",
            schedule: [
                { startDate: "2023-01-27", endDate: "2023-02-01", color: "#ff0000" },
                { startDate: "2023-03-27", endDate: "2023-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 8"],
        },
        {
            id: "RIS9",
            name: "Risorsa 9",
            schedule: [
                { startDate: "2023-01-01", endDate: "2023-02-01", color: "#ff0000" },
                { startDate: "2023-03-01", endDate: "2023-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 9"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    ganttHeight: 200,
    hideDependencies: true,
    filter: dummyFilter(),
    title: "Detail",
};

// planner 2
const mainGanttPlanner2PropsMock: GanttPlannerProps = {
    filter: dummyFilter(),
    items: [
        {
            id: "1",
            name: "G456",
            startDate: "2023-01-01",
            endDate: "2023-12-31",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G456", "#START#", "#END#"],
        },
        {
            id: "2",
            name: "G460",
            startDate: "2023-01-01",
            endDate: "2023-12-31",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G460", "#START#", "#END#"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    showSecondaryDates: false,
    ganttHeight: 350,
    hideDependencies: true,
    title: "Secondary",
};

const secondaryGanttPlanner2PropsMock: GanttPlannerDetailsProps = {
    filter: dummyFilter(),
    items: [
        {
            id: "RIS1",
            name: "Risorsa 1",
            schedule: [
                { startDate: "2023-01-01", endDate: "2027-02-01", color: "#ff0000" },
                { startDate: "2023-03-01", endDate: "2027-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 1"],
        },
        {
            id: "RIS2",
            name: "Risorsa 2",
            schedule: [
                { startDate: "2023-01-10", endDate: "2023-02-10", color: "#ff0000" },
                { startDate: "2023-03-10", endDate: "2023-04-10", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 2"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    ganttHeight: 200,
    hideDependencies: true,
    title: "Detail",
};

// planner 3
const mainGanttPlanner3PropsMock: GanttPlannerProps = {
    filter: dummyFilter(),
    items: [
        {
            id: "1",
            name: "G459",
            startDate: "2023-01-01",
            endDate: "2023-01-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G459", "#START#", "#END#"],
        },
        {
            id: "2",
            name: "G460",
            startDate: "2023-02-01",
            endDate: "2023-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G460", "#START#", "#END#"],
        },
        {
            id: "3",
            name: "G461",
            startDate: "2023-03-01",
            endDate: "2023-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G461", "#START#", "#END#"],
        },
        {
            id: "4",
            name: "G462",
            startDate: "2023-04-01",
            endDate: "2023-04-30",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G462", "#START#", "#END#"],
        },
        {
            id: "5",
            name: "G463",
            startDate: "2023-05-01",
            endDate: "2023-05-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G463", "#START#", "#END#"],
        },
        {
            id: "6",
            name: "G464",
            startDate: "2023-06-01",
            endDate: "2023-06-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G464", "#START#", "#END#"],
        },
        {
            id: "7",
            name: "G465",
            startDate: "2023-07-01",
            endDate: "2023-07-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G465", "#START#", "#END#"],
        },
        {
            id: "8",
            name: "G466",
            startDate: "2023-08-01",
            endDate: "2023-08-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G466", "#START#", "#END#"],
        },
        {
            id: "9",
            name: "G467",
            startDate: "2023-08-01",
            endDate: "2023-08-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G467", "#START#", "#END#"],
        },
        {
            id: "10",
            name: "G468",
            startDate: "2023-09-01",
            endDate: "2023-09-28",
            secondaryStartDate: "2021-11-25",
            secondaryEndDate: "2023-04-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G468", "#START#", "#END#"],
        },
        {
            id: "11",
            name: "G469",
            startDate: "2023-10-01",
            endDate: "2023-10-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G469", "#START#", "#END#"],
        },
        {
            id: "12",
            name: "G470",
            startDate: "2023-11-01",
            endDate: "2023-11-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G470", "#START#", "#END#"],
        },
        {
            id: "13",
            name: "G471",
            startDate: "2023-12-01",
            endDate: "2023-12-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G471", "#START#", "#END#"],
        },
        {
            id: "14",
            name: "G472",
            startDate: "2024-01-01",
            endDate: "2024-01-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G472", "#START#", "#END#"],
        },
        {
            id: "15",
            name: "G473",
            startDate: "2024-02-01",
            endDate: "2024-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            icon: {
                color: "#FF0000",
                url: "http://localhost:3000/assets/svg/alert-circle.svg",
            },
            valuesToShow: ["G473", "#START#", "#END#"],
        },
        {
            id: "16",
            name: "G474",
            startDate: "2024-03-01",
            endDate: "2024-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G474", "#START#", "#END#"],
        },
        {
            id: "17",
            name: "G475",
            startDate: "2024-04-01",
            endDate: "2024-04-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G475", "#START#", "#END#"],
        },
        {
            id: "18",
            name: "G476",
            startDate: "2024-05-01",
            endDate: "2024-05-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G476", "#START#", "#END#"],
        },
        {
            id: "19",
            name: "G477",
            startDate: "2024-06-01",
            endDate: "2024-06-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G477", "#START#", "#END#"],
        },
        {
            id: "20",
            name: "G478",
            startDate: "2024-07-01",
            endDate: "2024-07-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G478", "#START#", "#END#"],
        },
        {
            id: "21",
            name: "G479",
            startDate: "2024-08-01",
            endDate: "2024-08-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G479", "#START#", "#END#"],
        },
        {
            id: "22",
            name: "G480",
            startDate: "2024-09-01",
            endDate: "2024-09-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G480", "#START#", "#END#"],
        },
        {
            id: "23",
            name: "G481",
            startDate: "2024-10-01",
            endDate: "2024-10-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G481", "#START#", "#END#"],
        },
        {
            id: "24",
            name: "G482",
            startDate: "2024-11-01",
            endDate: "2024-11-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G482", "#START#", "#END#"],
        },
        {
            id: "25",
            name: "G483",
            startDate: "2024-12-01",
            endDate: "2024-12-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G483", "#START#", "#END#"],
        },
        {
            id: "26",
            name: "G484",
            startDate: "2025-01-01",
            endDate: "2025-01-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G484", "#START#", "#END#"],
        },
        {
            id: "27",
            name: "G485",
            startDate: "2025-02-01",
            endDate: "2025-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G485", "#START#", "#END#"],
        },
        {
            id: "28",
            name: "G486",
            startDate: "2025-03-01",
            endDate: "2025-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G486", "#START#", "#END#"],
        },
        {
            id: "29",
            name: "G487",
            startDate: "2025-04-01",
            endDate: "2025-04-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G487", "#START#", "#END#"],
        },
        {
            id: "30",
            name: "G488",
            startDate: "2025-05-01",
            endDate: "2025-05-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G488", "#START#", "#END#"],
        },
        {
            id: "31",
            name: "G479",
            startDate: "2026-08-01",
            endDate: "2026-08-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G479", "#START#", "#END#"],
        },
        {
            id: "32",
            name: "G480",
            startDate: "2026-09-01",
            endDate: "2026-09-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G480", "#START#", "#END#"],
        },
        {
            id: "33",
            name: "G481",
            startDate: "2026-10-01",
            endDate: "2026-10-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G481", "#START#", "#END#"],
        },
        {
            id: "34",
            name: "G482",
            startDate: "2026-11-01",
            endDate: "2026-11-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G482", "#START#", "#END#"],
        },
        {
            id: "35",
            name: "G483",
            startDate: "2026-12-01",
            endDate: "2026-12-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G483", "#START#", "#END#"],
        },
        {
            id: "36",
            name: "G484",
            startDate: "2027-01-01",
            endDate: "2027-01-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G484", "#START#", "#END#"],
        },
        {
            id: "37",
            name: "G485",
            startDate: "2027-02-01",
            endDate: "2027-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G485", "#START#", "#END#"],
        },
        {
            id: "38",
            name: "G486",
            startDate: "2027-03-01",
            endDate: "2027-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G486", "#START#", "#END#"],
        },
        {
            id: "39",
            name: "G487",
            startDate: "2027-04-01",
            endDate: "2027-04-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G487", "#START#", "#END#"],
        },
        {
            id: "40",
            name: "G488",
            startDate: "2027-05-01",
            endDate: "2027-05-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G488", "#START#", "#END#"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    showSecondaryDates: false,
    ganttHeight: 350,
    hideDependencies: true,
    title: "Main Gantt",
    initialScrollX: -1,
    initialScrollY: 500,
};

const secondaryGanttPlanner3PropsMock: GanttPlannerDetailsProps = {
    filter: dummyFilter(),
    items: [
        {
            id: "RIS1",
            name: "Risorsa 1",
            schedule: [
                { startDate: "2023-01-01", endDate: "2027-02-01", color: "#ff0000" },
                { startDate: "2023-03-01", endDate: "2027-04-01", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 1"],
        },
        {
            id: "RIS2",
            name: "Risorsa 2",
            schedule: [
                { startDate: "2023-01-10", endDate: "2023-02-10", color: "#ff0000" },
                { startDate: "2023-03-10", endDate: "2023-04-10", color: "#ff0000" },
            ],
            type: "timeline",
            valuesToShow: ["Risorsa 2"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    ganttHeight: 200,
    hideDependencies: true,
    title: "Detail",
};

// planner 4
const mainGanttPlanner4PropsMock: GanttPlannerProps = {
    filter: dummyFilter(),
    items: [
        {
            id: "1",
            name: "G459",
            startDate: "2023-01-01",
            endDate: "2023-01-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G459", "#START#", "#END#"],
        },
        {
            id: "2",
            name: "G460",
            startDate: "2023-02-01",
            endDate: "2023-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G460", "#START#", "#END#"],
        },
        {
            id: "3",
            name: "G461",
            startDate: "2023-03-01",
            endDate: "2023-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G461", "#START#", "#END#"],
        },
        {
            id: "4",
            name: "G462",
            startDate: "2023-04-01",
            endDate: "2023-04-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G462", "#START#", "#END#"],
        },
        {
            id: "5",
            name: "G463",
            startDate: "2023-05-01",
            endDate: "2023-05-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G463", "#START#", "#END#"],
        },
        {
            id: "6",
            name: "G464",
            startDate: "2023-06-01",
            endDate: "2023-06-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G464", "#START#", "#END#"],
        },
        {
            id: "7",
            name: "G465",
            startDate: "2023-07-01",
            endDate: "2023-07-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G465", "#START#", "#END#"],
        },
        {
            id: "8",
            name: "G466",
            startDate: "2023-08-01",
            endDate: "2023-08-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G466", "#START#", "#END#"],
        },
        {
            id: "9",
            name: "G467",
            startDate: "2023-09-01",
            endDate: "2023-09-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G467", "#START#", "#END#"],
        },
        {
            id: "10",
            name: "G468",
            startDate: "2023-10-01",
            endDate: "2023-10-28",
            secondaryStartDate: "2021-11-25",
            secondaryEndDate: "2023-04-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G468", "#START#", "#END#"],
        },
        {
            id: "11",
            name: "G469",
            startDate: "2023-11-01",
            endDate: "2023-11-28",
            secondaryStartDate: "2021-10-25",
            secondaryEndDate: "2023-03-07",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G469", "#START#", "#END#"],
        },
        {
            id: "12",
            name: "G470",
            startDate: "2023-12-01",
            endDate: "2023-12-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G470", "#START#", "#END#"],
        },
        {
            id: "13",
            name: "G471",
            startDate: "2024-01-01",
            endDate: "2024-01-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G471", "#START#", "#END#"],
        },
        {
            id: "14",
            name: "G472",
            startDate: "2024-02-01",
            endDate: "2024-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G472", "#START#", "#END#"],
        },
        {
            id: "15",
            name: "G473",
            startDate: "2024-03-01",
            endDate: "2024-03-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            icon: {
                color: "#FF0000",
                url: "http://localhost:3000/assets/svg/alert-circle.svg",
            },
            valuesToShow: ["G473", "#START#", "#END#"],
        },
        {
            id: "16",
            name: "G442",
            startDate: "2025-02-01",
            endDate: "2025-02-28",
            secondaryStartDate: "2021-10-20",
            secondaryEndDate: "2022-12-16",
            type: "project",
            phases: [],
            details: [],
            valuesToShow: ["G472", "#START#", "#END#"],
        },
    ],
    stylingOptions: {
        listCellWidth: "297px",
        rowHeight: 40,
        barFill: 90,
        projectProgressColor: "#CBCBCB",
        projectProgressSelectedColor: "#CBCBCB",
        projectBackgroundColor: "#CBCBCB",
        projectBackgroundSelectedColor: "#CBCBCB",
        barProgressColor: "#A2A415",
        barProgressSelectedColor: "#A2A415",
        barBackgroundColor: "#A2A415",
        barBackgroundSelectedColor: "#A2A415",
    },
    hideLabel: true,
    showSecondaryDates: false,
    ganttHeight: 350,
    hideDependencies: true,
    title: "Main Gantt",
    initialScrollX: -1,
    initialScrollY: 100,
    onScrollY: onScrollY
};

export const planner1PropsMock: PlannerProps = {
    mainGantt: mainGanttPlanner1PropsMock,
    secondaryGantt: secondaryGanttPlanner1PropsMock,
    viewMode: "month",
    onSetDoubleView: mainGanttDoubleViewHandler,
    onScrollX: onScrollX
};

export const planner2PropsMock: PlannerProps = {
    mainGantt: mainGanttPlanner2PropsMock,
    secondaryGantt: secondaryGanttPlanner2PropsMock,
    viewMode: "month",
};

export const planner3PropsMock: PlannerProps = {
    mainGantt: mainGanttPlanner3PropsMock,
    secondaryGantt: secondaryGanttPlanner3PropsMock,
    viewMode: "month",
};

export const planner4PropsMock: PlannerProps = {
    mainGantt: mainGanttPlanner4PropsMock,
    viewMode: "month",
};


export {
    mainGanttPlaner1Items,
    mainGanttPlaner1ItemsAfterClick
}
