import { KulThemeJSON } from './kul-theme-declarations';

export const themesJson: KulThemeJSON = {
    bubbles: {
        cssVariables: {
            '--kul-primary-color': '#c18f00',
            '--kul-secondary-color': '#1d1d1d',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#beb08d',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Lato, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '14px',
            '--kul-text-color': '#2e2e2e',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#5c5c5c',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#2e2e2e',
            '--kul-icon-color': '#505050',
            '--kul-border-color': '#e0e0e0',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#1D1D1B',
            '--kul-chart-color-1': '#ff5959',
            '--kul-chart-color-2': '#e0a0a0',
            '--kul-chart-color-3': '#8e1010',
            '--kul-chart-color-4': '#f5f5dc',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        icons: {
            '--kul-ascending-icon': 'sort-ascending',
            '--kul-descending-icon': 'sort-descending',
            '--kul-expanded-icon': 'chevron-down',
            '--kul-collapsed-icon': 'chevron_right',
            '--kul-dropdown-icon': 'chevron-down',
            '--kul-clear-icon': 'clear',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        isDark: false,
        customStyles: {},
        imports: [
            "@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap')",
        ],
    },
    cobalt: {
        cssVariables: {
            '--kul-primary-color': '#248aff',
            '--kul-secondary-color': '#65cbe9',
            '--kul-background-color': '#222222',
            '--kul-header-background-color': '#131313',
            '--kul-header-color': '#65cbe9',
            '--kul-drawer-background-color': '#2e2e2e',
            '--kul-drawer-color': '#65cbe9',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Blinker, sans-serif;',
            '--kul-font-family-monospace': 'Andalé Mono, monospace',
            '--kul-font-size': '14px',
            '--kul-text-color': '#65cbe9',
            '--kul-text-on-primary-color': '#f1f7ff',
            '--kul-text-on-secondary-color': '#000000',
            '--kul-disabled-background-color': '#3c3c3c',
            '--kul-disabled-color': '#7e7e7e',
            '--kul-title-background-color': '#2e2e2e',
            '--kul-title-color': '#f5f5f5',
            '--kul-icon-color': '#65cbe9',
            '--kul-border-color': '#535353',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#a4d9f7',
            '--kul-chart-color-1': '#308aff',
            '--kul-chart-color-2': '#5eb6d1',
            '--kul-chart-color-3': '#b1eafb',
            '--kul-chart-color-4': '#ffffff',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        isDark: true,
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Blinker:wght@200;300;600&display=swap')",
        ],
    },
    night: {
        cssVariables: {
            '--kul-primary-color': '#82f0e2',
            '--kul-secondary-color': '#f9ff00',
            '--kul-background-color': '#2d2d2d',
            '--kul-header-background-color': '#2d2d2d',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#1f1f1f',
            '--kul-drawer-color': '#f5f5f5',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Lato, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '14px',
            '--kul-text-color': '#f5f5f5',
            '--kul-text-on-primary-color': '#555555',
            '--kul-text-on-secondary-color': '#000000',
            '--kul-disabled-background-color': '#3c3c3c',
            '--kul-disabled-color': '#7e7e7e',
            '--kul-title-background-color': '#111111',
            '--kul-title-color': '#f5f5f5',
            '--kul-icon-color': '#e0e0e0',
            '--kul-border-color': '#535353',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#f2e114',
            '--kul-chart-color-1': '#60c3fc',
            '--kul-chart-color-2': '#e268d8',
            '--kul-chart-color-3': '#860bb5',
            '--kul-chart-color-4': '#1a83e4',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        isDark: true,
        imports: [
            "@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap')",
        ],
    },
    flamingo: {
        cssVariables: {
            '--kul-primary-color': '#e88aab',
            '--kul-secondary-color': '#7f00e7',
            '--kul-background-color': '#222222',
            '--kul-header-background-color': '#2d2d2d',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#1f1f1f',
            '--kul-drawer-color': '#f5f5f5',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Mali, cursive;',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '14px',
            '--kul-text-color': '#f5f5f5',
            '--kul-text-on-primary-color': '#000000',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#3c3c3c',
            '--kul-disabled-color': '#7e7e7e',
            '--kul-title-background-color': '#111111',
            '--kul-title-color': '#f5f5f5',
            '--kul-icon-color': '#e0e0e0',
            '--kul-border-color': '#535353',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#ffd0d8',
            '--kul-chart-color-1': '#e88aab',
            '--kul-chart-color-2': '#dc5584',
            '--kul-chart-color-3': '#c21350',
            '--kul-chart-color-4': '#c88da1',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        isDark: true,
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Mali:wght@300&display=swap')",
        ],
    },
    graphite: {
        cssVariables: {
            '--kul-primary-color': '#888888',
            '--kul-secondary-color': '#d91e18',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#535353',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#545454',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Roboto, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '13px',
            '--kul-text-color': '#545454',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-color': '#5c5c5c',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-title-background-color': '#f0f0f0',
            '--kul-title-color': '#545454',
            '--kul-icon-color': '#808080',
            '--kul-border-color': '#e0e0e0',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#eaa710',
            '--kul-chart-color-1': 'red',
            '--kul-chart-color-2': 'blue',
            '--kul-chart-color-3': 'orange',
            '--kul-chart-color-4': 'green',
            '--kul-chart-color-5': 'yellow',
            '--kul-chart-color-6': 'cyan',
            '--kul-chart-color-7': 'brown',
            '--kul-chart-color-8': 'magenta',
            '--kul-chart-color-9': 'grey',
            '--kul-chart-color-10': 'indigo',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        customStyles: {
            'kul-BUTTON':
                '#kul-component button {\ntext-transform: unset;\n}\n\n',
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
    },
    ketchup: {
        cssVariables: {
            '--kul-primary-color': '#d64325',
            '--kul-secondary-color': '#a6192e',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#2e2e2e',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#595959',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Ubuntu, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '14px',
            '--kul-text-color': '#595959',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#5c5c5c',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#2e2e2e',
            '--kul-icon-color': '#505050',
            '--kul-border-color': '#e0e0e0',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#eaa710',
            '--kul-chart-color-1': '#ff5959',
            '--kul-chart-color-2': '#e0a0a0',
            '--kul-chart-color-3': '#8e1010',
            '--kul-chart-color-4': '#f5f5dc',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'sort-ascending',
            '--kul-descending-icon': 'sort-descending',
            '--kul-expanded-icon': 'chevron-down',
            '--kul-collapsed-icon': 'chevron_right',
            '--kul-dropdown-icon': 'chevron-down',
            '--kul-clear-icon': 'clear',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;500&display=swap')",
        ],
    },
    obsidian: {
        cssVariables: {
            '--kul-primary-color': '#a6192e',
            '--kul-secondary-color': '#f5f4f4',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#000000',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#f5f4f4',
            '--kul-drawer-color': '#4c4c4d',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Open Sans, arial, helvatica',
            '--kul-font-family-monospace': 'Courier New, Courier, monospace',
            '--kul-font-size': '13px',
            '--kul-text-color': '#4c4c4d',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#a6192e',
            '--kul-disabled-background-color': '#ffffff',
            '--kul-disabled-color': '#4c4c4d',
            '--kul-title-background-color': '#068a9c',
            '--kul-title-color': '#ffffff',
            '--kul-icon-color': '#9d9d9d',
            '--kul-border-color': '#ededed',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#A6192E',
            '--kul-spinner-color': '#a6192e',
            '--kul-chart-color-1': '#735DED',
            '--kul-chart-color-2': '#00B2CB',
            '--kul-chart-color-3': '#EDC900',
            '--kul-chart-color-4': 'green',
            '--kul-chart-color-5': 'yellow',
            '--kul-chart-color-6': 'cyan',
            '--kul-chart-color-7': 'brown',
            '--kul-chart-color-8': 'magenta',
            '--kul-chart-color-9': 'grey',
            '--kul-chart-color-10': 'indigo',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap')",
        ],
    },
    ocean: {
        cssVariables: {
            '--kul-primary-color': '#0081c5',
            '--kul-secondary-color': '#3a8ede',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#001d3e',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#e6f1ff',
            '--kul-drawer-color': '#1b1b1b',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Open Sans Condensed, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '16px',
            '--kul-text-color': '#1b1b1b',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#5c5c5c',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#1b1b1b',
            '--kul-icon-color': '#505050',
            '--kul-border-color': '#e0e0e0',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#6edeff',
            '--kul-chart-color-1': '#60c3fc',
            '--kul-chart-color-2': '#e268d8',
            '--kul-chart-color-3': '#e48b47',
            '--kul-chart-color-4': '#81e447',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300;700&display=swap')",
        ],
    },
    print: {
        cssVariables: {
            '--kul-primary-color': '#000000',
            '--kul-secondary-color': '#cccccc',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#000000',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Arial, Helvetica, sans-serif',
            '--kul-font-family-monospace': 'Courier New, Courier, monospace',
            '--kul-font-size': '13px',
            '--kul-text-color': '#000000',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#000000',
            '--kul-disabled-background-color': '#ffffff',
            '--kul-disabled-color': '#000000',
            '--kul-title-background-color': '#f1f1f1',
            '--kul-title-color': '#000000',
            '--kul-icon-color': '#9d9d9d',
            '--kul-border-color': '#ededed',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#A6192E',
            '--kul-spinner-color': '#eaa710',
            '--kul-chart-color-1': '#735DED',
            '--kul-chart-color-2': '#00B2CB',
            '--kul-chart-color-3': '#EDC900',
            '--kul-chart-color-4': 'green',
            '--kul-chart-color-5': 'yellow',
            '--kul-chart-color-6': 'cyan',
            '--kul-chart-color-7': 'brown',
            '--kul-chart-color-8': 'magenta',
            '--kul-chart-color-9': 'grey',
            '--kul-chart-color-10': 'indigo',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        customStyles: {
            MASTER: '#kul-component #global-filter {\ndisplay: none;\n}\n\n',
            'kul-BOX':
                '#kul-component #box-container .box-wrapper .box:hover {\nbox-shadow: none;\n}\n\n#kul-component #box-container .box-wrapper .box.selected {\nbackground-color: inherit;\n}',
            'kul-BUTTON': ':host(:not(.printable)) {\ndisplay: none;\n}\n\n',
            'kul-CARD': '',
            'kul-DATA-TABLE':
                '#kul-component sticky-header {\ndisplay: none;\n}\n\n#kul-component kul-paginator {\ndisplay: none;\n}\n\n:host(.cross-selection) #kul-component table tr.selected td.selected, \n#kul-component table td.selected, #kul-component tr.selected td {\nbackground-color: inherit;\nbackground-image: none;\n}\n\n#kul-component table,\n#kul-component .below-wrapper {\noverflow: hidden !important;\n}\n\n:host(.cross-selection) #kul-component tr.selected td:first-of-type,\n:host(.cross-selection) #kul-component th.selected { \nbox-shadow: none !important;\n}\n\n:host(.cross-selection) #kul-component table td.selected,\n:host(.cross-selection) #kul-component table tr.selected td {\nbackground-color: inherit;\n}\n\n:host(.cross-selection) #kul-component table tr.selected td.fixed-column.selected,\n:host(.cross-selection) #kul-component table td.selected.fixed-column, \n:host(.cross-selection) #kul-component table td.selected.fixed-row,\n:host(.cross-selection) #kul-component table tr.selected td.fixed-column, \n:host(.cross-selection) #kul-component table tr.selected td.fixed-row {\nbackground-color: inherit;\nbackground-image: none;\n}\n\n',
            'kul-FAMILY-TREE':
                '#kul-component .family-tree__item__expand {\ndisplay: none;\n}\n\n',
            'kul-PROGRESS-BAR':
                '#kul-component .progress-bar {\nbackground: #e7e7e7;\n}\n\n#kul-component .progress-bar-percentage span {\ntext-shadow: 0px 0px 0px hsl(0deg 0% 100%);\n}\n\n',
            'kul-TREE':
                '#kul-component .wrapper {\noverflow: hidden;\n}\n\n#kul-component tr.mdc-ripple-surface::before, \n#kul-component tr.mdc-ripple-surface::after,\n#kul-component td.mdc-ripple-surface::before, \n#kul-component td.mdc-ripple-surface::after,\n#kul-component .kul-tree__node--selected:not(.kul-tree__node--disabled) td {\nbackground-color: var(--kul-background-color);\n}',
        },
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
    },
    raj: {
        cssVariables: {
            '--kul-primary-color': 'rgb(187, 198, 5)',
            '--kul-secondary-color': '#ffe600',
            '--kul-background-color': '#000000',
            '--kul-header-background-color': '#000000',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#000000',
            '--kul-drawer-color': '#ffffff',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': "'Rajdhani', sans-serif",
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '15px',
            '--kul-text-color': '#ffffff',
            '--kul-text-on-primary-color': '#000000',
            '--kul-text-on-secondary-color': '#000000',
            '--kul-disabled-background-color': '#151515',
            '--kul-disabled-color': '#7b7b7b',
            '--kul-title-background-color': '#ffe600',
            '--kul-title-color': '#000000',
            '--kul-icon-color': '#9d9d9d',
            '--kul-border-color': '#9d9d9d',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#ffe600',
            '--kul-chart-color-1': '#ffffff',
            '--kul-chart-color-2': 'rgb(187, 198, 5)',
            '--kul-chart-color-3': '#ffe600',
            '--kul-chart-color-4': '#effd02',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: true,
        icons: {
            '--kul-ascending-icon': 'sort-ascending',
            '--kul-descending-icon': 'sort-descending',
            '--kul-expanded-icon': 'chevron-down',
            '--kul-collapsed-icon': 'chevron_right',
            '--kul-dropdown-icon': 'chevron-down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&display=swap')",
        ],
    },
    red: {
        cssVariables: {
            '--kul-primary-color': '#a6192e',
            '--kul-secondary-color': '#ffc107',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#a6192e',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#f5f5f5',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Open Sans, arial, helvatica',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '13px',
            '--kul-text-color': '#000000',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#333333',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#2e2e2e',
            '--kul-icon-color': '#808080',
            '--kul-border-color': '#ededed',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#A6192E',
            '--kul-spinner-color': '#1D1D1B',
            '--kul-chart-color-1': '#735DED',
            '--kul-chart-color-2': '#00B2CB',
            '--kul-chart-color-3': '#EDC900',
            '--kul-chart-color-4': '#a6192e',
            '--kul-chart-color-5': 'yellow',
            '--kul-chart-color-6': 'cyan',
            '--kul-chart-color-7': 'brown',
            '--kul-chart-color-8': 'magenta',
            '--kul-chart-color-9': 'grey',
            '--kul-chart-color-10': 'indigo',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        customStyles: {},
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap')",
        ],
    },
    sapphire: {
        cssVariables: {
            '--kul-primary-color': '#003b77',
            '--kul-secondary-color': '#ff1414',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#003b77',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#002244',
            '--kul-drawer-color': '#ffffff',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '20em',
            '--kul-font-family': 'Arial',
            '--kul-font-family-monospace': 'Arial',
            '--kul-font-size': '13px',
            '--kul-text-color': '#333333',
            '--kul-text-on-primary-color': '#fafafa',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#ddecf8',
            '--kul-disabled-color': '#333333',
            '--kul-title-background-color': '#003b77',
            '--kul-title-color': '#ffffff',
            '--kul-icon-color': '#808080',
            '--kul-border-color': '#93c4ec',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#a94442',
            '--kul-spinner-color': '#003b77',
            '--kul-chart-color-1': '#0781fd',
            '--kul-chart-color-2': '#002244',
            '--kul-chart-color-3': '#c6cff8',
            '--kul-chart-color-4': '#66bdda',
            '--kul-chart-color-5': 'yellow',
            '--kul-chart-color-6': 'cyan',
            '--kul-chart-color-7': 'brown',
            '--kul-chart-color-8': 'magenta',
            '--kul-chart-color-9': 'grey',
            '--kul-chart-color-10': 'indigo',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        customStyles: {
            'kul-DATA-TABLE':
                '#kul-component th { --kul_datatable_th_border: none; font-weight: normal; }',
        },
    },
    silver: {
        cssVariables: {
            '--kul-primary-color': '#c0c0c0',
            '--kul-secondary-color': '#c0c0c0',
            '--kul-background-color': '#000000',
            '--kul-header-background-color': '#ffffff',
            '--kul-header-color': '#000000',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '80px',
            '--kul-drawer-width': '320px',
            '--kul-font-family': 'Oswald, sans-serif',
            '--kul-font-family-monospace': 'Xanh Mono, monospace',
            '--kul-font-size': '16px',
            '--kul-text-color': '#fefefe',
            '--kul-text-on-primary-color': '#4a4a4a',
            '--kul-text-on-secondary-color': '#4a4a4a',
            '--kul-disabled-background-color': '#3c3c3c',
            '--kul-disabled-color': '#7e7e7e',
            '--kul-title-background-color': '#151515',
            '--kul-title-color': '#d9d9d9',
            '--kul-icon-color': '#c0c0c0',
            '--kul-border-color': '#c0c0c0',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#c0c0c0',
            '--kul-chart-color-1': '#ffffff',
            '--kul-chart-color-2': '#b0b0b0',
            '--kul-chart-color-3': '#5c5c5c',
            '--kul-chart-color-4': '#000000',
            '--kul-chart-color-5': '#b35454',
            '--kul-chart-color-6': '#59af57',
            '--kul-chart-color-7': '#aeaa5d',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: true,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Xanh+Mono&display=swap')",
        ],
        customStyles: {},
    },
    teal: {
        cssVariables: {
            '--kul-primary-color': '#068A9C',
            '--kul-secondary-color': '#ffc107',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#068A9C',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#ffffff',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Roboto, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '13px',
            '--kul-text-color': '#000000',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#333333',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#2e2e2e',
            '--kul-icon-color': '#808080',
            '--kul-border-color': '#ededed',
            '--kul-box-shadow':
                'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#A6192E',
            '--kul-spinner-color': '#eaa710',
            '--kul-chart-color-1': '#068A9C',
            '--kul-chart-color-2': '#009643',
            '--kul-chart-color-3': '#EDC900',
            '--kul-chart-color-4': '#188F00',
            '--kul-chart-color-5': '#758700',
            '--kul-chart-color-6': '#7D2F00',
            '--kul-chart-color-7': '#710008',
            '--kul-chart-color-8': '#640056',
            '--kul-chart-color-9': '#1C0056',
            '--kul-chart-color-10': '#000046',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
    },
    wildlife: {
        cssVariables: {
            '--kul-primary-color': '#0fa918',
            '--kul-secondary-color': '#739f5a',
            '--kul-background-color': '#ffffff',
            '--kul-header-background-color': '#095a1f',
            '--kul-header-color': '#ffffff',
            '--kul-drawer-background-color': '#dbfbd5',
            '--kul-drawer-color': '#000000',
            '--kul-header-height': '64px',
            '--kul-drawer-width': '300px',
            '--kul-font-family': 'Abel, sans-serif',
            '--kul-font-family-monospace': 'Roboto Mono, consolas, monospace',
            '--kul-font-size': '16px',
            '--kul-text-color': '#000000',
            '--kul-text-on-primary-color': '#ffffff',
            '--kul-text-on-secondary-color': '#ffffff',
            '--kul-disabled-background-color': '#eaeaea',
            '--kul-disabled-color': '#5c5c5c',
            '--kul-title-background-color': '#f1f3f4',
            '--kul-title-color': '#000000',
            '--kul-icon-color': '#333333',
            '--kul-border-color': '#e0e0e0',
            '--kul-box-shadow': '0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)',
            '--kul-info-color': '#2592df',
            '--kul-success-color': '#4d9f02',
            '--kul-warning-color': '#ffc107',
            '--kul-danger-color': '#d91e18',
            '--kul-spinner-color': '#44b383',
            '--kul-chart-color-1': '#60c3fc',
            '--kul-chart-color-2': '#e268d8',
            '--kul-chart-color-3': '#e48b47',
            '--kul-chart-color-4': '#81e447',
            '--kul-obj-cursor': 'inherit',
            '--kul-card-zindex': 900,
            '--kul-drawer-zindex': 900,
            '--kul-header-zindex': 900,
        },
        isDark: false,
        icons: {
            '--kul-ascending-icon': 'arrow_drop_up',
            '--kul-descending-icon': 'arrow_drop_down',
            '--kul-expanded-icon': 'arrow_drop_down',
            '--kul-collapsed-icon': 'menu-right',
            '--kul-dropdown-icon': 'arrow_drop_down',
            '--kul-clear-icon': 'cancel',
            '--kul-filter-remove-icon': 'filter-remove',
            '--kul-key-icon': 'key-variant',
            '--kul-search-icon': 'search',
            '--kul-warning-icon': 'warning',
        },
        imports: [
            "url('https://fonts.googleapis.com/css2?family=Abel&display=swap')",
        ],
    },
};
