import type { GenericObject } from '../../types/GenericTypes';

/**
 * Variable used to fetch the MASTER customStyle (used in every component).
 */
export const masterCustomStyle = 'MASTER';
/**
 * Interface of the themes JSON.
 */
export interface KupThemeJSON {
    [index: string]: KupThemeVariables;
}
/**
 * Interface wrapping all the others.
 */
export interface KupThemeVariables {
    cssVariables: KupThemeCSSVariables;
    icons: KupThemeIcons;
    customStyles?: GenericObject;
    imports?: string[];
}
/**
 * All CSS variables managed by KupTheme.
 */
export interface KupThemeCSSVariables {
    '--kup-primary-color': string;
    '--kup-secondary-color': string;
    '--kup-background-color': string;
    '--kup-nav-bar-background-color': string;
    '--kup-drawer-background-color': string;
    '--kup-font-family': string;
    '--kup-font-size': string;
    '--kup-text-color': string;
    '--kup-text-on-primary-color': string;
    '--kup-disabled-background-color': string;
    '--kup-disabled-color': string;
    '--kup-hover-background-color': string;
    '--kup-hover-color': string;
    '--kup-title-background-color': string;
    '--kup-title-color': string;
    '--kup-icon-color': string;
    '--kup-border-color': string;
    '--kup-box-shadow': string;
    '--kup-field-background-color': string;
    '--kup-success-color': string;
    '--kup-warning-color': string;
    '--kup-danger-color': string;
    '--kup-spinner-color': string;
    '--kup-chart-color-1': string;
    '--kup-chart-color-2': string;
    '--kup-chart-color-3': string;
    '--kup-chart-color-4': string;
    '--kup-font-family-monospace': string;
    '--kup-obj-cursor': string;
    '--kup-text-on-secondary-color': string;
}
/**
 * All icons managed by KupTheme.
 */
export interface KupThemeIcons {
    '--kup-ascending-icon': string;
    '--kup-clear-icon': string;
    '--kup-collapsed-icon': string;
    '--kup-descending-icon': string;
    '--kup-expanded-icon': string;
    '--kup-filter-remove-icon': string;
}
/**
 * All RGB variables automatically generated by KupTheme.
 * Defined as generic to avoid double declaration.
 * Every CSS variable containing the string "color" will automatically generate a RGB variable.
 */
export interface KupThemeCSSVariablesRGB {
    [key: string]: string;
}
