/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@sme.up/ketchup';

import { defineCustomElements } from '@sme.up/ketchup/dist/loader';

defineCustomElements();
export const KupAccordion = /*@__PURE__*/createReactComponent<JSX.KupAccordion, HTMLKupAccordionElement>('kup-accordion');
export const KupActivityTimeline = /*@__PURE__*/createReactComponent<JSX.KupActivityTimeline, HTMLKupActivityTimelineElement>('kup-activity-timeline');
export const KupAutocomplete = /*@__PURE__*/createReactComponent<JSX.KupAutocomplete, HTMLKupAutocompleteElement>('kup-autocomplete');
export const KupBadge = /*@__PURE__*/createReactComponent<JSX.KupBadge, HTMLKupBadgeElement>('kup-badge');
export const KupBox = /*@__PURE__*/createReactComponent<JSX.KupBox, HTMLKupBoxElement>('kup-box');
export const KupButton = /*@__PURE__*/createReactComponent<JSX.KupButton, HTMLKupButtonElement>('kup-button');
export const KupButtonList = /*@__PURE__*/createReactComponent<JSX.KupButtonList, HTMLKupButtonListElement>('kup-button-list');
export const KupCalendar = /*@__PURE__*/createReactComponent<JSX.KupCalendar, HTMLKupCalendarElement>('kup-calendar');
export const KupCard = /*@__PURE__*/createReactComponent<JSX.KupCard, HTMLKupCardElement>('kup-card');
export const KupCardList = /*@__PURE__*/createReactComponent<JSX.KupCardList, HTMLKupCardListElement>('kup-card-list');
export const KupCell = /*@__PURE__*/createReactComponent<JSX.KupCell, HTMLKupCellElement>('kup-cell');
export const KupChart = /*@__PURE__*/createReactComponent<JSX.KupChart, HTMLKupChartElement>('kup-chart');
export const KupCheckbox = /*@__PURE__*/createReactComponent<JSX.KupCheckbox, HTMLKupCheckboxElement>('kup-checkbox');
export const KupChip = /*@__PURE__*/createReactComponent<JSX.KupChip, HTMLKupChipElement>('kup-chip');
export const KupColorPicker = /*@__PURE__*/createReactComponent<JSX.KupColorPicker, HTMLKupColorPickerElement>('kup-color-picker');
export const KupCombobox = /*@__PURE__*/createReactComponent<JSX.KupCombobox, HTMLKupComboboxElement>('kup-combobox');
export const KupCustomTaskListHeader = /*@__PURE__*/createReactComponent<JSX.KupCustomTaskListHeader, HTMLKupCustomTaskListHeaderElement>('kup-custom-task-list-header');
export const KupCustomTaskListTable = /*@__PURE__*/createReactComponent<JSX.KupCustomTaskListTable, HTMLKupCustomTaskListTableElement>('kup-custom-task-list-table');
export const KupDashboard = /*@__PURE__*/createReactComponent<JSX.KupDashboard, HTMLKupDashboardElement>('kup-dashboard');
export const KupDataTable = /*@__PURE__*/createReactComponent<JSX.KupDataTable, HTMLKupDataTableElement>('kup-data-table');
export const KupDatePicker = /*@__PURE__*/createReactComponent<JSX.KupDatePicker, HTMLKupDatePickerElement>('kup-date-picker');
export const KupDialog = /*@__PURE__*/createReactComponent<JSX.KupDialog, HTMLKupDialogElement>('kup-dialog');
export const KupDrawer = /*@__PURE__*/createReactComponent<JSX.KupDrawer, HTMLKupDrawerElement>('kup-drawer');
export const KupDropdownButton = /*@__PURE__*/createReactComponent<JSX.KupDropdownButton, HTMLKupDropdownButtonElement>('kup-dropdown-button');
export const KupEchart = /*@__PURE__*/createReactComponent<JSX.KupEchart, HTMLKupEchartElement>('kup-echart');
export const KupEditor = /*@__PURE__*/createReactComponent<JSX.KupEditor, HTMLKupEditorElement>('kup-editor');
export const KupFamilyTree = /*@__PURE__*/createReactComponent<JSX.KupFamilyTree, HTMLKupFamilyTreeElement>('kup-family-tree');
export const KupForm = /*@__PURE__*/createReactComponent<JSX.KupForm, HTMLKupFormElement>('kup-form');
export const KupGantt = /*@__PURE__*/createReactComponent<JSX.KupGantt, HTMLKupGanttElement>('kup-gantt');
export const KupGanttCalendar = /*@__PURE__*/createReactComponent<JSX.KupGanttCalendar, HTMLKupGanttCalendarElement>('kup-gantt-calendar');
export const KupGauge = /*@__PURE__*/createReactComponent<JSX.KupGauge, HTMLKupGaugeElement>('kup-gauge');
export const KupGrid = /*@__PURE__*/createReactComponent<JSX.KupGrid, HTMLKupGridElement>('kup-grid');
export const KupGridRenderer = /*@__PURE__*/createReactComponent<JSX.KupGridRenderer, HTMLKupGridRendererElement>('kup-grid-renderer');
export const KupHorizontalScroll = /*@__PURE__*/createReactComponent<JSX.KupHorizontalScroll, HTMLKupHorizontalScrollElement>('kup-horizontal-scroll');
export const KupHtm = /*@__PURE__*/createReactComponent<JSX.KupHtm, HTMLKupHtmElement>('kup-htm');
export const KupIframe = /*@__PURE__*/createReactComponent<JSX.KupIframe, HTMLKupIframeElement>('kup-iframe');
export const KupImage = /*@__PURE__*/createReactComponent<JSX.KupImage, HTMLKupImageElement>('kup-image');
export const KupImageList = /*@__PURE__*/createReactComponent<JSX.KupImageList, HTMLKupImageListElement>('kup-image-list');
export const KupInputPanel = /*@__PURE__*/createReactComponent<JSX.KupInputPanel, HTMLKupInputPanelElement>('kup-input-panel');
export const KupLazy = /*@__PURE__*/createReactComponent<JSX.KupLazy, HTMLKupLazyElement>('kup-lazy');
export const KupList = /*@__PURE__*/createReactComponent<JSX.KupList, HTMLKupListElement>('kup-list');
export const KupMagicBox = /*@__PURE__*/createReactComponent<JSX.KupMagicBox, HTMLKupMagicBoxElement>('kup-magic-box');
export const KupNavBar = /*@__PURE__*/createReactComponent<JSX.KupNavBar, HTMLKupNavBarElement>('kup-nav-bar');
export const KupNumericPicker = /*@__PURE__*/createReactComponent<JSX.KupNumericPicker, HTMLKupNumericPickerElement>('kup-numeric-picker');
export const KupPdf = /*@__PURE__*/createReactComponent<JSX.KupPdf, HTMLKupPdfElement>('kup-pdf');
export const KupPhotoFrame = /*@__PURE__*/createReactComponent<JSX.KupPhotoFrame, HTMLKupPhotoFrameElement>('kup-photo-frame');
export const KupPlanner = /*@__PURE__*/createReactComponent<JSX.KupPlanner, HTMLKupPlannerElement>('kup-planner');
export const KupPlannerRenderer = /*@__PURE__*/createReactComponent<JSX.KupPlannerRenderer, HTMLKupPlannerRendererElement>('kup-planner-renderer');
export const KupProbe = /*@__PURE__*/createReactComponent<JSX.KupProbe, HTMLKupProbeElement>('kup-probe');
export const KupProgressBar = /*@__PURE__*/createReactComponent<JSX.KupProgressBar, HTMLKupProgressBarElement>('kup-progress-bar');
export const KupQlik = /*@__PURE__*/createReactComponent<JSX.KupQlik, HTMLKupQlikElement>('kup-qlik');
export const KupRadio = /*@__PURE__*/createReactComponent<JSX.KupRadio, HTMLKupRadioElement>('kup-radio');
export const KupRating = /*@__PURE__*/createReactComponent<JSX.KupRating, HTMLKupRatingElement>('kup-rating');
export const KupSnackbar = /*@__PURE__*/createReactComponent<JSX.KupSnackbar, HTMLKupSnackbarElement>('kup-snackbar');
export const KupSpinner = /*@__PURE__*/createReactComponent<JSX.KupSpinner, HTMLKupSpinnerElement>('kup-spinner');
export const KupStandardTooltip = /*@__PURE__*/createReactComponent<JSX.KupStandardTooltip, HTMLKupStandardTooltipElement>('kup-standard-tooltip');
export const KupSwitch = /*@__PURE__*/createReactComponent<JSX.KupSwitch, HTMLKupSwitchElement>('kup-switch');
export const KupSwitcher = /*@__PURE__*/createReactComponent<JSX.KupSwitcher, HTMLKupSwitcherElement>('kup-switcher');
export const KupTabBar = /*@__PURE__*/createReactComponent<JSX.KupTabBar, HTMLKupTabBarElement>('kup-tab-bar');
export const KupTaskGantt = /*@__PURE__*/createReactComponent<JSX.KupTaskGantt, HTMLKupTaskGanttElement>('kup-task-gantt');
export const KupTaskList = /*@__PURE__*/createReactComponent<JSX.KupTaskList, HTMLKupTaskListElement>('kup-task-list');
export const KupTaskListHeader = /*@__PURE__*/createReactComponent<JSX.KupTaskListHeader, HTMLKupTaskListHeaderElement>('kup-task-list-header');
export const KupTaskListTable = /*@__PURE__*/createReactComponent<JSX.KupTaskListTable, HTMLKupTaskListTableElement>('kup-task-list-table');
export const KupTextField = /*@__PURE__*/createReactComponent<JSX.KupTextField, HTMLKupTextFieldElement>('kup-text-field');
export const KupTimePicker = /*@__PURE__*/createReactComponent<JSX.KupTimePicker, HTMLKupTimePickerElement>('kup-time-picker');
export const KupTooltip = /*@__PURE__*/createReactComponent<JSX.KupTooltip, HTMLKupTooltipElement>('kup-tooltip');
export const KupTree = /*@__PURE__*/createReactComponent<JSX.KupTree, HTMLKupTreeElement>('kup-tree');
export const KupTypography = /*@__PURE__*/createReactComponent<JSX.KupTypography, HTMLKupTypographyElement>('kup-typography');
export const KupTypographyList = /*@__PURE__*/createReactComponent<JSX.KupTypographyList, HTMLKupTypographyListElement>('kup-typography-list');
export const KupVerticalScroll = /*@__PURE__*/createReactComponent<JSX.KupVerticalScroll, HTMLKupVerticalScrollElement>('kup-vertical-scroll');
