name: test

on:
    push:
        branches:
        - feat/ga
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
            with:
              node-version: '16.x'
              registry-url: 'https://registry.npmjs.org'
          - run:  |
              pwd
              cd packages/ketchup
              pwd
              node scripts/k-npm-snapshot.js
              cd ../ketchup-react
              pwd
              node scripts/kr-npm-snapshot.js
              cd ../..
              pwd
              npm install yarn
              node -v
              yarn -v
              yarn cache clean --all
              yarn install
              npm run k:build
          # - run: npm run publish:snapshot
          #   env:
          #     NODE_AUTH_TOKEN: {{ secrets.NPM_TOKEN }}