name: Ketchup Unit Test

on:
    pull_request:
        branches:
            - develop
            - master

env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    PUPPETEER_SKIP_DOWNLOAD: true

jobs:
    unit-test:
        runs-on: ubuntu-latest
        concurrency:
            group: generate-docs-${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.16.0'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run build
              run: npm run k:build

            - name: Execute tests
              run: npm run k:test:unit
